In [2]:
import cv2
import pandas

In [19]:
image = cv2.imread("aura.tif", cv2.IMREAD_UNCHANGED)

In [24]:
for bits in range(8):
    for idx, clr in enumerate("bgr"):
        cv2.imwrite(f"{clr}@{bits + 1}.png", (image[:, :, idx] & 2 ** bits) * (256 / 2 ** bits))

In [21]:
df = pandas.DataFrame(image[:,:,0])
df = df.map(lambda v: "{0:b}".format(v)[-6:])
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,886,887,888,889,890,891,892,893,894,895
count,896,896,896,896,896,896,896,896,896,896,...,896,896,896,896,896,896,896,896,896,896
unique,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,111,111,111,111,111,111,111,111,111,111,...,111,111,111,111,111,111,111,111,111,111
freq,896,896,896,896,896,896,896,896,896,896,...,896,896,896,896,896,896,896,896,896,896